name: release

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-docs.txt

    - name: Build
      shell: bash -l {0}
      run: |
        mkdocs build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
